util.AddNetworkString("RoundStart")
util.AddNetworkString("RoundActive")
util.AddNetworkString("RoundEnded")
util.AddNetworkString("TimerChanged")
util.AddNetworkString("BroadcastSound")
util.AddNetworkString("UpdateStamina")