util.AddNetworkString("BroadcastSound")
util.AddNetworkString("TimerChanged")
util.AddNetworkString("StaminaChanged")
util.AddNetworkString("RoundStateChanged")
util.AddNetworkString("ShowRoundSummary")