

ALL_CLASSES = {
    classds = {
        name = "Class D Personnel",
        color = Color(255, 130, 0),
        roles = {
            {
                name = ROLES.ROLE_CLASSD,
                team = TEAM_CLASS_D,
                weapons = { "br_holster" },
                showweapons = {},
                ammo = {},
                health = 100,
                armor = 0,
                walkspeed = 1,
                runspeed = 1,
                jumppower = 1,
                vest = nil,
                models = CLASS_D_MODELS,
                showmodel = nil,
                level = 0,
                customcheck = nil,
                flashlight = false,
                max = 64
            },
            {
                name = ROLES.ROLE_VETERAN,
                team = TEAM_CLASS_D,
                weapons = { "br_holster" },
                showweapons = {},
                ammo = {},
                health = 120,
                armor = 0,
                walkspeed = 1.1,
                runspeed = 1.05,
                jumppower = 1.05,
                vest = nil,
                models = CLASS_D_MODELS,
                showmodel = nil,
                flashlight = false,
                level = 6,
                max = 4
            }
        }
    },
    misc_staff = {
        name = "Misc Staff",
        color = Color(141, 58, 196),
        roles = {
            {
                name = ROLES.ROLE_JANITOR,
                team = TEAM_STAFF,
                weapons = { "br_holster", "keycard_level1" },
                showweapons = { "Keycard Level 1" },
                ammo = {},
                health = 100,
                armor = 0,
                walkspeed = 1,
                runspeed = 1,
                jumppower = 1,
                vest = nil,
                models = STAFF_MODELS,
                showmodel = nil,
                pmcolor = Color(50, 50, 50),
                flashlight = true,
                level = 0,
                max = 12
            },
            {
                name = ROLES.ROLE_ENG,
                team = TEAM_STAFF,
                weapons = { "br_holster", "keycard_level2", "item_gasmask" },
                showweapons = { "Keycard Level 2", "Gas Mask" },
                ammo = {},
                health = 110,
                armor = 0,
                walkspeed = 1,
                runspeed = 1,
                jumppower = 1,
                vest = nil,
                models = STAFF_MODELS,
                showmodel = nil,
                pmcolor = Color(50, 50, 50),
                flashlight = true,
                level = 1,
                max = 1
            },
            {
                name = ROLES.ROLE_MEDIC,
                team = TEAM_STAFF,
                weapons = { "br_holster", "keycard_level2", "item_ultramedkit", "item_eyedrops" },
                showweapons = { "Keycard Level 2", "Med Kit", "Eyedrops" },
                ammo = {},
                health = 100,
                armor = 0,
                walkspeed = 1,
                runspeed = 1,
                jumppower = 1,
                vest = nil,
                models = STAFF_MODELS,
                showmodel = nil,
                pmcolor = Color(50, 50, 50),
                flashlight = true,
                level = 2,
                max = 1
            }
        }
    },
    research_staff = {
        name = "Research Staff",
        color = Color(66, 188, 244),
        roles = {
            {
                name = ROLES.ROLE_RES,
                team = TEAM_SCIENTIST,
                weapons = { "br_holster", "keycard_level2" },
                showweapons = { "Keycard Level 2" },
                ammo = {},
                health = 100,
                armor = 0,
                walkspeed = 1,
                runspeed = 1,
                jumppower = 1,
                vest = nil,
                models = RESEARCHER_MODELS,
                showmodel = RESEARCHER_MODELS[1],
                flashlight = true,
                level = 0,
                max = 36
            },
            {
                name = ROLES.ROLE_HRES,
                team = TEAM_SCIENTIST,
                weapons = { "br_holster", "keycard_level3" },
                showweapons = { "Keycard Level 3" },
                ammo = {},
                health = 100,
                armor = 0,
                walkspeed = 1,
                runspeed = 1,
                jumppower = 1,
                vest = nil,
                models = RESEARCHER_MODELS,
                showmodel = RESEARCHER_MODELS[1],
                flashlight = true,
                level = 3,
                max = 1
            }
        }
    },
    security = {
        name = "Site Security",
        color = Color(0, 100, 255),
        roles = {
            {
                name = ROLES.ROLE_SEC_GUARD,
                team = TEAM_GUARD,
                weapons = { "br_holster", "keycard_level2", "item_radio", "item_gasmask", "weapon_stunstick", "weapon_mtf_tmp" },
                showweapons = { "Keycard Level 2", "Radio", "Gas Mask", "Stunstick", "TMP" },
                ammo = { { "SMG1", 200 } },
                health = 100,
                armor = 0,
                walkspeed = 1,
                runspeed = 1,
                jumppower = 1,
                vest = "armor_sec_guard",
                models = RESEARCHER_MODELS,
                showmodel = "models/player/kerry/class_securety.mdl",
                pmcolor = nil,
                flashlight = true,
                level = 0,
                max = 8,
                sorting = 0,
                importancelevel = 1
            },
            {
                name = ROLES.ROLE_SEC_OFFICER,
                team = TEAM_GUARD,
                weapons = { "br_holster", "keycard_level3", "item_radio", "item_gasmask", "weapon_stunstick", "weapon_mtf_p90" },
                showweapons = { "Keycard Level 3", "Radio", "Gas Mask", "Stunstick", "P90" },
                ammo = { { "SMG1", 200 } },
                health = 100,
                armor = 0,
                walkspeed = 1,
                runspeed = 1,
                jumppower = 1,
                vest = "armor_sec_officer",
                models = RESEARCHER_MODELS,
                showmodel = "models/fart/ragdolls/css/counter_gign_player.mdl",
                pmcolor = nil,
                flashlight = true,
                level = 1,
                max = 8,
                sorting = 5,
                importancelevel = 2
            },
            {
                name = ROLES.ROLE_SEC_MEDIC,
                team = TEAM_GUARD,
                weapons = { "br_holster", "keycard_level3", "item_radio", "item_gasmask", "item_ultramedkit", "weapon_stunstick", "weapon_mtf_ump45" },
                showweapons = { "Keycard Level 3", "Radio", "Gas Mask", "Med Kit", "Stunstick", "UMP" },
                ammo = { { "SMG1", 200 } },
                health = 100,
                armor = 0,
                walkspeed = 1,
                runspeed = 1,
                jumppower = 1,
                vest = "armor_sec_officer",
                models = RESEARCHER_MODELS,
                showmodel = "models/fart/ragdolls/css/counter_gign_player.mdl",
                pmcolor = nil,
                flashlight = true,
                level = 2,
                max = 1,
                sorting = 6,
                importancelevel = 2
            },
            {
                name = ROLES.ROLE_SEC_CHIEF,
                team = TEAM_GUARD,
                weapons = { "br_holster", "keycard_level4", "item_radio", "item_gasmask", "item_nvg", "weapon_stunstick", "weapon_mtf_mp5" },
                showweapons = { "Keycard Level 4", "Radio", "Gas Mask", "NVG", "Stunstick", "MP5" },
                ammo = { { "SMG1", 200 } },
                health = 100,
                armor = 0,
                walkspeed = 1,
                runspeed = 1,
                jumppower = 1,
                vest = "armor_sec_chief",
                models = RESEARCHER_MODELS,
                showmodel = "models/mtf/mtf remasteredhd.mdl",
                pmcolor = nil,
                flashlight = true,
                level = 4,
                max = 1,
                sorting = 7,
                importancelevel = 3,
                players_min = 7
            },
            {
                name = ROLES.ROLE_SD,
                team = TEAM_GUARD,
                weapons = { "br_holster", "keycard_level5", "item_radio", "item_gasmask", "weapon_stunstick", "weapon_mtf_deagle" },
                showweapons = { "Keycard Level 5", "Radio", "Gas Mask", "Stunstick", "Desert Eagle" },
                ammo = { { "Pistol", 105 } },
                health = 100,
                armor = 0,
                walkspeed = 1,
                runspeed = 1,
                jumppower = 1,
                vest = nil,
                models = RESEARCHER_MODELS,
                showmodel = "models/player/breen.mdl",
                pmcolor = Color(0, 0, 0),
                flashlight = true,
                level = 6,
                max = 1,
                sorting = 8,
                importancelevel = 4,
                players_min = 16
            },
        }
    },
    chaosins = {
        name = "Chaos Insurgency",
        color = Color(126, 160, 32),
        sc_color = Color(126, 160, 32),
        roles = {
            {
                name = ROLES.ROLE_CI_RES,
                disguised_name = ROLES.ROLE_RES,
                disguised_sorting = "research_staff",
                disguised_color = Color(66, 188, 244),
                team = TEAM_CHAOS,
                weapons = { "br_holster", "keycard_level3" },
                showweapons = { "Keycard Level 3" },
                ammo = {},
                health = 100,
                armor = 0,
                walkspeed = 1,
                runspeed = 1,
                jumppower = 1,
                vest = nil,
                models = RESEARCHER_MODELS,
                showmodel = RESEARCHER_MODELS[1],
                flashlight = true,
                level = 0,
                max = 2
            },
            {
                name = ROLES.ROLE_CI_GUARD,
                disguised_name = ROLES.ROLE_SEC_OFFICER,
                disguised_sorting = "security",
                disguised_color = Color(0, 100, 255),
                team = TEAM_CHAOS,
                weapons = { "br_holster", "keycard_level3", "item_radio", "item_gasmask", "weapon_stunstick", "weapon_mtf_p90" },
                showweapons = { "Keycard Level 3", "Radio", "Gas Mask", "Stunstick", "P90" },
                ammo = { { "SMG1", 200 } },
                health = 100,
                armor = 0,
                walkspeed = 1,
                runspeed = 1,
                jumppower = 1,
                vest = "armor_sec_officer",
                models = RESEARCHER_MODELS,
                showmodel = "models/fart/ragdolls/css/counter_gign_player.mdl",
                pmcolor = nil,
                flashlight = true,
                level = 1,
                max = 1
            },
            {
                name = ROLES.ROLE_CI_SOLD,
                disguised_name = ROLES.ROLE_SEC_OFFICER,
                disguised_sorting = "security",
                disguised_color = Color(0, 100, 255),
                team = TEAM_CHAOS,
                weapons = { "br_holster", "keycard_omni", "item_radio", "item_gasmask", "item_nvg", "weapon_stunstick", "weapon_chaos_ak47" },
                showweapons = { "Keycard Omni", "Radio", "Gas Mask", "NVG", "Stunstick", "AK47" },
                ammo = { { "AR2", 180 } },
                health = 100,
                armor = 0,
                walkspeed = 1,
                runspeed = 1,
                jumppower = 1,
                vest = "armor_chaos",
                models = CHAOS_MODELS,
                showmodel = "models/friskiukas/bf4/us_01.mdl",
                pmcolor = nil,
                flashlight = true,
                level = 2,
                max = 1
            },
        }
    },
    support = {
        name = "Site Support",
        color = Color(29, 81, 56),
        sc_color = Color(0, 100, 255),
        roles = {
            {
                name = ROLES.ROLE_CHAOS,
                disguised_name = ROLES.ROLE_MTF_OFFICER,
                team = TEAM_CHAOS,
                weapons = { "br_holster", "keycard_omni", "item_radio", "item_gasmask", "item_nvg", "weapon_stunstick", "weapon_chaos_ak47" },
                showweapons = { "Keycard Omni", "Radio", "Gas Mask", "NVG", "Stunstick", "AK47" },
                ammo = { { "AR2", 180 } },
                health = 100,
                armor = 0,
                walkspeed = 1,
                runspeed = 1,
                jumppower = 1,
                vest = "armor_chaos",
                models = CHAOS_MODELS,
                showmodel = "models/friskiukas/bf4/us_01.mdl",
                pmcolor = nil,
                flashlight = true,
                level = 1,
                max = 24
            },
            {
                name = ROLES.ROLE_MTF_OFFICER,
                team = TEAM_GUARD,
                weapons = { "br_holster", "keycard_level4", "item_radio", "item_gasmask", "item_nvg", "weapon_stunstick", "weapon_chaos_famas" },
                showweapons = { "Keycard Level 4", "Radio", "Gas Mask", "NVG", "Stunstick", "FAMAS" },
                ammo = { { "AR2", 180 } },
                health = 100,
                armor = 0,
                walkspeed = 1,
                runspeed = 1,
                jumppower = 1,
                vest = "armor_mtf_officer",
                models = RESEARCHER_MODELS,
                showmodel = "models/fart/ragdolls/css/counter_sas_player.mdl",
                pmcolor = nil,
                flashlight = true,
                level = 1,
                max = 24
            },
            {
                name = ROLES.ROLE_MTF_MEDIC,
                team = TEAM_GUARD,
                weapons = { "br_holster", "keycard_level4", "item_radio", "item_gasmask", "item_nvg", "item_ultramedkit", "weapon_stunstick", "weapon_chaos_famas" },
                showweapons = { "Keycard Level 4", "Radio", "Gas Mask", "NVG", "Med Kit", "Stunstick", "FAMAS" },
                ammo = { { "AR2", 180 } },
                health = 100,
                armor = 0,
                walkspeed = 1,
                runspeed = 1,
                jumppower = 1,
                vest = "armor_mtf_medic",
                models = RESEARCHER_MODELS,
                showmodel = "models/payday2/units/medic_player.mdl",
                pmcolor = nil,
                flashlight = true,
                level = 2,
                max = 1
            },
            {
                name = ROLES.ROLE_MTF_SCU,
                team = TEAM_GUARD,
                weapons = { "br_holster", "keycard_level4", "item_radio", "item_gasmask", "item_nvg", "weapon_stunstick", "weapon_chaos_m249" },
                showweapons = { "Keycard Level 4", "Radio", "Gas Mask", "NVG", "Stunstick", "M249" },
                ammo = { { "AR2", 180 } },
                health = 100,
                armor = 0,
                walkspeed = 1,
                runspeed = 1,
                jumppower = 1,
                vest = "armor_mtf_officer",
                models = RESEARCHER_MODELS,
                showmodel = "models/fart/ragdolls/css/counter_sas_player.mdl",
                pmcolor = nil,
                flashlight = true,
                level = 3,
                max = 2
            },
            {
                name = ROLES.ROLE_CHAOSCOM,
                team = TEAM_CHAOS,
                disguised_name = ROLES.ROLE_MTF_OFFICER,
                weapons = { "br_holster", "keycard_omni", "item_radio", "item_gasmask", "item_nvg", "weapon_stunstick", "weapon_mtf_deagle", "weapon_chaos_xm1014" },
                showweapons = { "Keycard Omni", "Radio", "Gas Mask", "NVG", "Stunstick", "Desert Eagle", "XM1014" },
                ammo = { { "Buckshot", 32 }, { "Pistol", 105 } },
                health = 100,
                armor = 0,
                walkspeed = 1,
                runspeed = 1,
                jumppower = 1,
                vest = "armor_chaos",
                models = CHAOS_MODELS,
                showmodel = "models/friskiukas/bf4/us_01.mdl",
                pmcolor = nil,
                flashlight = true,
                level = 4,
                max = 1
            },
            {
                name = ROLES.ROLE_MTF_SNIPER,
                team = TEAM_GUARD,
                weapons = { "br_holster", "keycard_level4", "item_radio", "item_gasmask", "item_nvg", "weapon_stunstick", "weapon_mtf_usp", "weapon_chaos_sg550" },
                showweapons = { "Keycard Level 4", "Radio", "Gas Mask", "NVG", "Stunstick", "USP", "SG550" },
                ammo = { { "AR2", 180 }, { "Pistol", 105 } },
                health = 100,
                armor = 0,
                walkspeed = 1,
                runspeed = 1,
                jumppower = 1,
                vest = "armor_mtf_officer",
                models = RESEARCHER_MODELS,
                showmodel = "models/fart/ragdolls/css/counter_sas_player.mdl",
                pmcolor = nil,
                flashlight = true,
                level = 4,
                max = 1
            },
            {
                name = ROLES.ROLE_MTF_LIE,
                team = TEAM_GUARD,
                weapons = { "br_holster", "keycard_level4", "item_radio", "item_gasmask", "item_nvg", "weapon_stunstick", "weapon_chaos_famas" },
                showweapons = { "Keycard Level 4", "Radio", "Gas Mask", "NVG", "Stunstick", "FAMAS" },
                ammo = { { "AR2", 180 } },
                health = 100,
                armor = 0,
                walkspeed = 1,
                runspeed = 1,
                jumppower = 1,
                vest = "armor_mtf_lie",
                models = RESEARCHER_MODELS,
                showmodel = "models/mw2/skin_03/mw2_soldier_04.mdl",
                pmcolor = nil,
                flashlight = true,
                level = 5,
                max = 2
            },
            {
                name = ROLES.ROLE_MTF_COM,
                team = TEAM_GUARD,
                weapons = { "br_holster", "keycard_level4", "item_radio", "item_gasmask", "item_nvg", "weapon_stunstick", "weapon_mtf_deagle", "weapon_chaos_ak47" },
                showweapons = { "Keycard Level 4", "Radio", "Gas Mask", "NVG", "Stunstick", "Desert Eagle", "AK47" },
                ammo = { { "AR2", 180 }, { "Pistol", 105 } },
                health = 100,
                armor = 0,
                walkspeed = 1,
                runspeed = 1,
                jumppower = 1,
                vest = "armor_mtf_com",
                models = RESEARCHER_MODELS,
                showmodel = "models/player/riot.mdl",
                pmcolor = nil,
                flashlight = true,
                level = 6,
                max = 1
            },
        }
    }
}

ROLE_LIST_CLASSDS = 1 -- 4 - 8
ROLE_LIST_SCPS = 2 -- 2 - 5
ROLE_LIST_MISC_STAFF = 3 -- 2 - 4
ROLE_LIST_RESEARCH_STAFF = 4 -- 3 - 5
ROLE_LIST_SECURITY = 5 -- 3 - 6
ROLE_LIST_CHAOSINS = 6 -- 2 - 4
ROLE_LIST_MTF = 7
ROLE_LIST_CI = 8
Breach_Default_Role_List = {
    -- 1 - 16	{4, 2, 2, 3, 3, 2}
    ROLE_LIST_CLASSDS,
    ROLE_LIST_SCPS,
    ROLE_LIST_SECURITY,
    ROLE_LIST_MISC_STAFF,
    ROLE_LIST_CLASSDS,
    ROLE_LIST_RESEARCH_STAFF,
    ROLE_LIST_CHAOSINS,
    ROLE_LIST_SECURITY,
    ROLE_LIST_SCPS,
    ROLE_LIST_CLASSDS,
    ROLE_LIST_RESEARCH_STAFF,
    ROLE_LIST_SECURITY,
    ROLE_LIST_CLASSDS,
    ROLE_LIST_MISC_STAFF,
    ROLE_LIST_CHAOSINS,
    ROLE_LIST_RESEARCH_STAFF,
    -- 2 - 32	{8, 5, 4, 5, 6, 4}
    ROLE_LIST_CLASSDS,
    ROLE_LIST_SECURITY,
    ROLE_LIST_SCPS,
    ROLE_LIST_CHAOSINS,
    ROLE_LIST_CLASSDS,
    ROLE_LIST_MISC_STAFF,
    ROLE_LIST_SECURITY,
    ROLE_LIST_SCPS,
    ROLE_LIST_CLASSDS,
    ROLE_LIST_RESEARCH_STAFF,
    ROLE_LIST_MISC_STAFF,
    ROLE_LIST_CHAOSINS,
    ROLE_LIST_SECURITY,
    ROLE_LIST_SCPS,
    ROLE_LIST_RESEARCH_STAFF,
    ROLE_LIST_CLASSDS,
}